[package]
name = "kubix-validator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argh = "0.1.13"
jsonschema = "0.37.4"
k8s-openapi = { version = "0.26.0", features = ["v1_34"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
